version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: ci/jenkins:1.0
    privileged: true
    build: ./jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./workspace/jenkins/jenkins_home:/var/jenkins_home
      - ./workspace/jenkins/jenkins_log:/var/log/jenkins
      # setup configurations
      - ./jenkins/casc_configs/:/var/jenkins_home/casc_configs/
      